interface RedditCommentsJsonResponse {
    kind: "listing";
    data: {
        modhash: string;
        dist: number;
        before: string | null;
        after: string;
        children: Array<{
            kind: "t1";
            data: {
                awarders: [];
                total_awards_received: 0;
                approved_at_utc: null;
                link_title: string;
                mod_reason_by: null;
                banned_by: null;
                author_flair_type: string;
                removal_reason: null;
                link_id: string;
                author_flair_template_id: string;
                likes: null;
                replies: "";
                user_reports: [];
                saved: false;
                id: string;
                banned_at_utc: null;
                mod_reason_title: null;
                gilded: 0;
                archived: boolean;
                no_follow: boolean;
                author: string;
                num_comments: number;
                can_mod_post: boolean;
                created_utc: number;
                send_replies: boolean;
                parent_id: string;
                score: number;
                author_fullname: string;
                over_18: boolean;
                approved_by: null;
                mod_note: null;
                all_awardings: [];
                subreddit_id: string;
                body: string;
                edited: boolean;
                author_flair_css_class: string;
                name: string;
                steward_reports: [];
                author_patreon_flair: boolean;
                downs: 0;
                author_flair_richtext: any[];
                is_submitter: boolean;
                body_html: string;
                gildings: {};
                collapsed_reason: null;
                distinguished: null;
                associated_award: null;
                stickied: boolean;
                can_gild: boolean;
                subreddit: string;
                author_flair_text_color: string;
                score_hidden: boolean;
                permalink: string;
                num_reports: null;
                link_permalink: string;
                report_reasons: null;
                link_author: string;
                author_flair_text: string | null;
                link_url: string;
                created: number;
                collapsed: boolean;
                subreddit_name_prefixed: string;
                controversiality: number;
                locked: boolean;
                author_flair_background_color: string;
                collapsed_because_crowd_control: null;
                mod_reports: [];
                quarantine: boolean;
                subreddit_type: string;
                ups: number;
            };
        }>;
    };
}

interface SubredditJsonResponse {
    kind: string,
    data: {
        user_flair_background_color: null,
        submit_text_html: string,
        restrict_posting: boolean,
        user_is_banned: boolean,
        free_form_reports: boolean,
        wiki_enabled: boolean,
        user_is_muted: boolean,
        user_can_flair_in_sr: null,
        display_name: string,
        header_img: string,
        title: string,
        icon_size: [number, number],
        primary_color: string,
        active_user_count: number,
        icon_img: string,
        display_name_prefixed: string,
        accounts_active: number,
        public_traffic: boolean,
        subscribers: number,
        user_flair_richtext: [],
        name: string,
        quarantine: boolean,
        hide_ads: boolean,
        emojis_enabled: boolean,
        advertiser_category: string,
        public_description: string,
        comment_score_hide_mins: number,
        user_has_favorited: boolean,
        user_flair_template_id: null,
        community_icon: string,
        banner_background_image: string,
        original_content_tag_enabled: boolean,
        submit_text: string,
        description_html: string,
        spoilers_enabled: boolean,
        header_title: string,
        header_size: [number, number],
        user_flair_position: string,
        all_original_content: boolean,
        has_menu_widget: boolean,
        is_enrolled_in_new_modmail: null,
        key_color: string,
        can_assign_user_flair: boolean,
        created: number,
        wls: number,
        show_media_preview: boolean,
        submission_type: string,
        user_is_subscriber: boolean,
        disable_contributor_requests: boolean,
        allow_videogifs: boolean,
        user_flair_type: string,
        collapse_deleted_comments: boolean,
        emojis_custom_size: null,
        public_description_html: string,
        allow_videos: boolean,
        is_crosspostable_subreddit: null,
        notification_level: null,
        can_assign_link_flair: boolean,
        accounts_active_is_fuzzed: boolean,
        submit_text_label: null,
        link_flair_position: string,
        user_sr_flair_enabled: boolean,
        user_flair_enabled_in_sr: boolean,
        allow_discovery: boolean,
        user_sr_theme_enabled: boolean,
        link_flair_enabled: boolean,
        subreddit_type: string,
        suggested_comment_sort: null,
        banner_img: string,
        user_flair_text: null,
        banner_background_color: string,
        show_media: boolean,
        id: string,
        user_is_moderator: boolean,
        overnumber: boolean,
        description: string,
        submit_link_label: null,
        user_flair_text_color: null,
        restrict_commenting: boolean,
        user_flair_css_class: null,
        allow_images: boolean,
        lang: string,
        whitelist_status: string,
        url: string,
        created_utc: number,
        banner_size: [number, number],
        mobile_banner_image: string,
        user_is_contributor: boolean
    }
}


export { RedditCommentsJsonResponse, SubredditJsonResponse }